import http from './configs/apiConfig.js';
// 获取session
export const getSessionId = params => http.get('account/sessionId', params);
// 用户登录
export const wxLogin = params => http.post('account/signInByWeApp', params);
// 获取用户信息 
export const getPeople = params => http.get('people/findById', params);
// 获取系统信息：GET app/findById
export const auth = params => http.post('publicWxLogin',params) 
export const usable_cash = params => http.get('usable_cash', params)
export const disable_cash = params => http.get('disable_cash', params)
export const create_qrcode = params => http.get('create_qrcode', params) 
export const get_cash = params => http.get('get_cash', params)
export const getNum = params => http.get('getNum', params)
export const user_info = params => http.get('user_info',params)
export const getAppMsg = params => http.get('app/findById', params);
export const get_address = params => http.get('get_address',params)
export const add_address = params => http.post('add_address',params)
export const del_address = params => http.get('del_address',params)
export const update_address = params =>http.post('update_address',params)
export const searchGroupBuilkMessage = params => http.post('searchGroupBuilkMessage', params)
export const default_address = params => http.get('default_address',params)
//测试
export const shop_info = params => http.get('shop_info', params)
export const shop_color = params => http.get('shop_color', params)
export const sel_cate = params => http.get('sel_cate', params)
export const tea_goods_show = params => http.get('tea_goods_show', params)
export const goods_info = params => http.get('goods_info', params)
export const teaPay = params => http.post('teaPay', params)
export const my_cash = params => http.get('my_cash', params)
export const new_order = params => http.post('new_order', params)
export const cut_order = params => http.post('cut_order', params)
export const print_pro = params => http.get('print_pro', params)
export const meituan_index = params => http.post('meituan_index', params)
export const wait = params => http.get('wait', params)
export const receive = params => http.get('receive', params)
export const finish = params => http.get('finish', params)
export const goodsDetail = params => http.get('goodsDetail', params)
export const newTeaGoods = params => http.get('newTeaGoods', params)
export const confirmGroups = params => http.post('confirmGroups', params)
export const getOrderInfo = params => http.get('getOrderInfo', params)
export const getDistriBution = params => http.get('getDistriBution', params)
export const admin_shop_info = params => http.get('admin_shop_info', params)
export const isUserInfo = params => http.get('isUserInfo', params)
export const getUserMoney = params => http.get('getUserMoney', params)
export const getShopJuLi = params => http.get('getShopJuLi', params)
export const group_cash = params => http.post('group_cash', params)
export const get_groupCash = params => http.get('get_groupCash', params)
export const getFormIdInfo = params => http.get('getFormIdInfo', params)
export const addShopCard = params => http.post('addShopCard', params)
export const addAftermarketService = params => http.post('addAftermarketService', params)
export const upAftermarketOrder = params => http.post('upAftermarketOrder', params)
export const aftermarketOrder = params => http.get('aftermarketOrder', params)
export const businessAftermarketOrder = params => http.get('businessAftermarketOrder', params)
export const newWaitOrder = params => http.get('newWaitOrder', params)
export const dada_index = params => http.post('dada_index', params)
export const dada_cancel = params => http.post('dada_cancel', params)
export const redada_index = params => http.post('redada_index', params)
export const get_dada_status = params => http.get('get_dada_status', params)
export const get_groups = params => http.get('get_groups', params)
export const group_status = params => http.get('group_status', params)
export const cash_list = params => http.get('cash_list', params)